<?php

$fruits = array(
    "Abiu",
    "Acerola",
    "Akebi",
    "Ackee",
    "African Cherry Orange",
    "American Mayapple",
    "Apple",
    "Apricot",
    "Araza",
    "Avocado",
    "Banana",
    "Bilberry",
    "Blackberry",
    "Blackcurrant",
    "Black sapote",
    "Blueberry",
    "Boysenberry",
    "Breadfruit",
    "Buddha's hand",
    "Cactus pear",
    "Canistel",
    "Cashew",
    "Cempedak",
    "Cherimoya",
    "Cherry",
    "Chico fruit",
    "Cloudberry",
    "Coco De Mer",
    "Coconut",
    "Crab apple",
    "Cranberry",
    "Currant",
    "Damson",
    "Date",
    "Dragonfruit",
    "Pitaya",
    "Durian",
    "Egg Fruit",
    "Elderberry",
    "Feijoa",
    "Fig",
    "Finger Lime",
    "Caviar Lime",
    "Goji berry",
    "Gooseberry",
    "Grape",
    "Raisin",
    "Grapefruit",
    "Grewia asiatica (phalsa or falsa)",
    "Guava",
    "Hala Fruit",
    "Honeyberry",
    "Huckleberry",
    "Jabuticaba",
    "Jackfruit",
    "Jambul",
    "Japanese plum",
    "Jostaberry",
    "Jujube",
    "Juniper berry",
    "Kaffir Lime",
    "Kiwano",
    "Kiwifruit",
    "Kumquat",
    "Lemon",
    "Lime",
    "Loganberry",
    "Longan",
    "Loquat",
    "Lulo",
    "Lychee",
    "Magellan Barberry",
    "Mamey Apple",
    "Mamey Sapote",
    "Mango",
    "Mangosteen",
    "Marionberry",
    "Melon",
    "Cantaloupe",
    "Galia melon",
    "Honeydew",
    "Mouse melon",
    "Musk melon",
    "Watermelon",
    "Miracle fruit",
    "Momordica fruit",
    "Monstera deliciosa",
    "Mulberry",
    "Nance",
    "Nectarine",
    "Orange",
    "Blood orange",
    "Clementine",
    "Mandarine",
    "Tangerine",
    "Papaya",
    "Passionfruit",
    "Pawpaw",
    "Peach",
    "Pear",
    "Persimmon",
    "Plantain",
    "Plum",
    "Prune",
    "Pineapple",
    "Pineberry",
    "Plumcot",
    "Pomegranate",
    "Pomelo",
    "Purple mangosteen",
    "Quince",
    "Raspberry",
    "Salmonberry",
    "Rambutan",
    "Redcurrant",
    "Rose apple",
    "Salal",
    "Salak",
    "Sapodilla",
    "Sapote",
    "Satsuma",
    "Shine Muscat or Vitis Vinifera",
    "Sloe or Hawthorn Berry",
    "Soursop",
    "Star apple",
    "Star fruit",
    "Strawberry",
    "Surinam cherry",
    "Tamarillo",
    "Tamarind",
    "Tangelo",
    "Tayberry",
    "Ugli fruit",
    "White currant",
    "White sapote",
    "Ximenia",
    "Yuzu"
);

$fruitMap = array_map('_create_fruit', $fruits);

// query param
$q = (isset($_REQUEST['q'])) ? $_REQUEST['q'] : '';

// if there is not query params show all and stop process
if (!$q) {
    echo json_encode($fruitMap);
    die();
}

$fruitsMapFilter = array_filter($fruitMap, function ($fruit) use ($q) {
    return stripos($fruit['name'], $q) !== false;
});

echo json_encode(array_values($fruitsMapFilter));

function _create_fruit($name){
    return array(
        'name' => $name,
    );
}